default: &default
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  port: 3306
  host: localhost

development:
  <<: *default
  database: sobi_development

test:
  <<: *default
  database: sobi_test

production:
  <<: *default
  database: sobi_production
